name: m3ml
description: M3ml Challenge
author: Ziny Programmers
version: 0.0.1+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5+1
  firebase_auth: ^0.6.2+1
  firebase_messaging: ^2.0.2
  firebase_storage: ^1.0.4
  firebase_analytics: ^1.0.4
  firebase_database: ^1.0.5
  google_sign_in: ^3.2.1
  validate: ^1.7.0
  image_picker: ^0.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/ # Images Dir
  - assets/lang/ # Lang Json Dir